#!/usr/bin/env python3
"""
Generate explicit ``jupedsim.escalator_comb`` records for the conveyor escalator model.

Each escalator is drawn as one corridor strip per level; together the two strips
are the escalator's plan-view footprint. The old model teleported agents between
the strips at their *inner* ends (the ``esc.X.zone.*`` transfer zones), i.e.
halfway up the incline. The real combs — where people step on and off — are
the strips' *outer* ends: the corridor edge farthest from that level's transfer
zone. This script derives, per escalator:

* the entry comb (boarding level) and exit comb (other level) as segments,
* the unit normal pointing from each comb onto its landing floor,
* the incline length (sum of the two strips' long sides),
* the egress target on the exit side (from the existing arrival metadata),

and checks that the landing in front of every comb is open floor once the
corridors are removed. Records are written inside a generated block at the end
of each level file, replacing any previous block, so re-running is idempotent.

Usage:
    python scripts/generate_escalator_combs.py            # print + check only
    python scripts/generate_escalator_combs.py --write    # update level XML files
"""

from __future__ import annotations

import argparse
import math
import re
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

from shapely import make_valid
from shapely.geometry import Point, Polygon
from shapely.ops import unary_union

NETWORK = Path(__file__).resolve().parents[1] / "geometry" / "monument" / "network"
LEVELS = ("-1", "0")
BEGIN = (
    "    <!-- escalator combs: generated by scripts/generate_escalator_combs.py — do not edit -->"
)
END = "    <!-- end escalator combs -->"


def _shape(text: str) -> list[tuple[float, float]]:
    return [tuple(map(float, p.split(","))) for p in text.split()]


def _poly(text: str):
    return make_valid(Polygon(_shape(text)))


def load_level(level: str) -> dict:
    root = ET.parse(NETWORK / f"level_{level}.xml").getroot()
    polys = root.findall(".//poly")
    return {
        "walkable": {
            p.get("name") or p.get("id"): _poly(p.get("shape"))
            for p in polys
            if p.get("type") == "jupedsim.walkable_area"
        },
        "obstacles": [_poly(p.get("shape")) for p in polys if p.get("type") == "jupedsim.obstacle"],
        "corridors": {
            p.get("name"): Polygon(_shape(p.get("shape")))
            for p in polys
            if p.get("type") == "jupedsim.escalator"
        },
        "endpoints": [
            dict(p.attrib) for p in polys if p.get("type") == "jupedsim.escalator_endpoint"
        ],
    }


def floor_without_escalators(level: dict):
    cut = unary_union(
        list(level["corridors"].values())
        + [p for n, p in level["walkable"].items() if n.startswith("esc.")]
    )
    walk = unary_union([p for n, p in level["walkable"].items() if not n.startswith("esc.")])
    return walk.difference(unary_union(level["obstacles"])).difference(cut.buffer(0.02))


def comb_for(corridor: Polygon, transfer_zone: Polygon):
    """Outer short edge of the strip, its outward floor normal, and the strip length."""
    pts = list(corridor.exterior.coords)[:-1]
    edges = [(pts[i], pts[(i + 1) % len(pts)]) for i in range(len(pts))]
    ref = transfer_zone.centroid
    a, b = max(
        edges,
        key=lambda e: math.dist(((e[0][0] + e[1][0]) / 2, (e[0][1] + e[1][1]) / 2), (ref.x, ref.y)),
    )
    mid = ((a[0] + b[0]) / 2, (a[1] + b[1]) / 2)
    ex, ey = b[0] - a[0], b[1] - a[1]
    n = math.hypot(ex, ey)
    nx, ny = -ey / n, ex / n
    c = corridor.centroid
    if nx * (c.x - mid[0]) + ny * (c.y - mid[1]) > 0:  # point away from the strip
        nx, ny = -nx, -ny
    rect = corridor.minimum_rotated_rectangle
    r = list(rect.exterior.coords)
    length = max(math.dist(r[0], r[1]), math.dist(r[1], r[2]))
    return a, b, (nx, ny), length


def build() -> list[dict]:
    levels = {lvl: load_level(lvl) for lvl in LEVELS}
    floors = {lvl: floor_without_escalators(levels[lvl]) for lvl in LEVELS}
    by_letter: dict[str, dict] = {}
    for lvl, data in levels.items():
        for ep in data["endpoints"]:
            letter = ep["endpoint_id"].split("_")[0]
            corridor = data["corridors"][ep["corridor"]]
            tz = data["walkable"][ep["transfer_zone"]]
            a, b, normal, length = comb_for(corridor, tz)
            entry = by_letter.setdefault(letter, {"letter": letter})
            side = "entry" if ep["role"] == "departure" else "exit"
            entry[side] = {"level": lvl, "a": a, "b": b, "normal": normal, "strip_length": length}
            if side == "entry":
                entry["exit_name"] = ep["exit_name"]
            elif ep.get("egress_x"):
                entry["egress"] = (float(ep["egress_x"]), float(ep["egress_y"]))

    records = []
    problems = []
    for letter, e in sorted(by_letter.items()):
        if "entry" not in e or "exit" not in e:
            problems.append(f"{letter}: missing entry or exit endpoint")
            continue
        e["direction"] = "up" if e["entry"]["level"] == "-1" else "down"
        e["length_m"] = e["entry"]["strip_length"] + e["exit"]["strip_length"]
        for side in ("entry", "exit"):
            c = e[side]
            mid = ((c["a"][0] + c["b"][0]) / 2, (c["a"][1] + c["b"][1]) / 2)
            landing = Point(mid[0] + c["normal"][0] * 0.6, mid[1] + c["normal"][1] * 0.6)
            ok = floors[c["level"]].buffer(-0.2).contains(landing)
            c["landing_ok"] = ok
            if not ok:
                problems.append(
                    f"{letter} {side} (level {c['level']}): landing point "
                    f"{landing.x:.2f},{landing.y:.2f} is not open floor"
                )
        records.append(e)
    return records, problems


def render(records: list[dict], level: str) -> list[str]:
    lines = []
    for e in records:
        for side in ("entry", "exit"):
            c = e[side]
            if c["level"] != level:
                continue
            (x1, y1), (x2, y2) = c["a"], c["b"]
            attrs = [
                f'id="jps.escalator_comb_{e["letter"]}_{side}"',
                f'name="escalator_{e["letter"]}_comb_{side}"',
                'type="jupedsim.escalator_comb"',
                f'escalator="{e["letter"]}"',
                f'role="{side}"',
                f'exit_name="{e["exit_name"]}"',
                f'direction="{e["direction"]}"',
                f'length_m="{e["length_m"]:.2f}"',
                f'floor_nx="{round(c["normal"][0], 4) + 0.0:.4f}" floor_ny="{round(c["normal"][1], 4) + 0.0:.4f}"',
            ]
            if side == "exit" and "egress" in e:
                attrs.append(f'egress_x="{e["egress"][0]:.2f}" egress_y="{e["egress"][1]:.2f}"')
            attrs.append(
                f'color="255,140,0" fill="0" layer="1.60" shape="{x1:.3f},{y1:.3f} {x2:.3f},{y2:.3f}"'
            )
            lines.append("    <poly " + " ".join(attrs) + "/>")
    return lines


def write(level: str, lines: list[str]) -> None:
    path = NETWORK / f"level_{level}.xml"
    text = path.read_text()
    text = re.sub(re.escape(BEGIN) + r".*?" + re.escape(END) + r"\n", "", text, flags=re.S)
    block = "\n".join([BEGIN, *lines, END]) + "\n"
    idx = text.rindex("</additional>")
    path.write_text(text[:idx] + block + text[idx:])


def main() -> int:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument("--write", action="store_true", help="Update the level XML files")
    args = parser.parse_args()

    records, problems = build()
    for e in records:
        ent, ext = e["entry"], e["exit"]
        print(
            f"{e['exit_name']:18s} {e['direction']:4s} length {e['length_m']:5.2f} m  "
            f"entry L{ent['level']} width {math.dist(ent['a'], ent['b']):.2f} m  "
            f"exit L{ext['level']} width {math.dist(ext['a'], ext['b']):.2f} m"
        )
    for p in problems:
        print("  PROBLEM:", p, file=sys.stderr)
    if args.write:
        for level in LEVELS:
            write(level, render(records, level))
            print(f"wrote combs to level_{level}.xml")
    return 1 if problems else 0


if __name__ == "__main__":
    sys.exit(main())
